const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(__dirname + '/../renderer/app.js', 'utf8');
const match = source.match(/function setHintsVisible\(visible\) \{[\s\S]*?\n\}/);
assert.ok(match, 'Unified recommendation display control exists');
const controls = {'chk-show': {}, 'pick-show-hints': {}};
const saved = new Map();
let draws = 0;
const context = {state:{showHints:false}, $:id=>controls[id], localStorage:{setItem:(k,v)=>saved.set(k,v)}, draw:()=>draws++};
vm.createContext(context);
vm.runInContext(match[0], context);
context.setHintsVisible(true);
assert.equal(context.state.showHints,true);
assert.equal(controls['chk-show'].checked,true);
assert.equal(controls['pick-show-hints'].checked,true);
assert.equal(saved.get('rapacego.showHints'),'true');
context.setHintsVisible(false);
assert.equal(controls['chk-show'].checked,false);
assert.equal(controls['pick-show-hints'].checked,false);
assert.equal(saved.get('rapacego.showHints'),'false');
assert.equal(draws,2);
context.localStorage.setItem=()=>{throw new Error('storage unavailable')};
context.setHintsVisible(true);
assert.equal(context.state.showHints,true,'Storage failure must not block interaction');
console.log('Recommendation display, synchronized controls, persistence and storage failure passed');
